'use client';

import Footer from '@/components/shared/Footer/Footer';
import Navbar from '@/components/shared/Navbar/Navbar';
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className} suppressHydrationWarning={true} >
        <div className="container">
          <Navbar />
          {children}
          <ProgressBar
            height="4px"
            color="#BC3433"
            options={{ showSpinner: false }}
            shallowRouting
          />
          <Footer />
        </div>
      </body>

    </html>
  )
}
